POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "username" : "mirkomiric@gmail.com",
  "password" : "123"
}

> {% client.global.set("auth_token", response.body.accessToken); %}

###

POST http://localhost:8081/api/v1/admin
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name" : "Andrija",
  "lastName" : "Vojnovic",
  "phoneNumber" : "225883",
  "accountNumber" : "12345663434",
  "emailAddress" : "andrijavojnovicpa@gmail.com",
  "password" : "123"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

###

GET http://localhost:8081/api/v1/admin/
Authorization: Bearer {{auth_token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}


###

